end_mode: PE
read_files:
  - class: File
    format: 'edam:format_1930'
    path: $CWL_DATA_DIR/datasets/$left_file
  - class: File
    format: 'edam:format_1930'
    path: $CWL_DATA_DIR/datasets/$right_file 
forward_reads:
  class: File
  format: 'edam:format_1930'
  path: $CWL_DATA_DIR/datasets/$left_file 
reverse_reads:
  class: File
  format: 'edam:format_1930'
  path: $CWL_DATA_DIR/datasets/$right_file
trinity_seq_type: fq
trinity_max_mem: 4G
trinity_ss_lib_type: FR
trinity_cpu: 4
